# This is a basic workflow to help you get started with Actions

name: SGSI编译

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 下载SGSI工具
        run: |
          wget https://github.com/xiaoxindada/SGSI-build-tool/releases/download/v1.0/SGSI-build-tool.tar
          tar -xf SGSI-build-tool.tar
          sudo chmod -R 777 SGSI-build-tool
          cd SGSI-build-tool/10
          ./setup.sh

      # Runs a set of commands using the runners shell
      - name: 编译SGSI
        run: |
          wget https://hugeota.d.miui.com/20.8.27/miui_RAPHAEL_20.8.27_fa77c41115_10.0.zip
          mv miui_RAPHAEL_20.8.27_fa77c41115_10.0.zip tmp
          sudo ./SGSI.zip
